name: Lint Dockerfile

on: push

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Hypermodern Image
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "hypermodern/Dockerfile"

